version: "3"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=80
    networks:
      - bridge_service
  bridge-service:
    image: bmusuko/bridge-service
    env_file:
      - "./.env"
    ports:
      - 8085:8085
    networks:
      - bridge_service
    depends_on:
      - docker-host

networks:
  bridge_service:
    driver: bridge
    name: bridge_service
