version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - "./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/"
        - "./docker-conf/rabbitmq/log/:/var/log/rabbitmq"
    networks:
        - bridge_service

networks:
  bridge_service:
    driver: bridge
    name: bridge_service
